Turn off the hash rocket check for rubocop
Running with this cop on with `no_mixed_keys` results in an exception
for certain files:

```
undefined method `loc' for nil:NilClass
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
cop/style/hash_syntax.rb:124:in `no_mixed_keys_check'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
cop/style/hash_syntax.rb:88:in `on_hash'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
cop/commissioner.rb:41:in `block (2 levels) in on_hash'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
cop/commissioner.rb:96:in `with_cop_error_handling'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
cop/commissioner.rb:40:in `block in on_hash'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
cop/commissioner.rb:39:in `each'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
cop/commissioner.rb:39:in `on_hash'
(eval):3:in `on_optarg'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
cop/commissioner.rb:45:in `on_optarg'
(eval):2:in `block in on_args'
(eval):2:in `each'
(eval):2:in `on_args'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
cop/commissioner.rb:45:in `on_args'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
ast_node/traversal.rb:152:in `on_block'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
cop/commissioner.rb:45:in `on_block'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
cop/commissioner.rb:45:in `on_begin'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
ast_node/traversal.rb:12:in `walk'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
cop/commissioner.rb:58:in `investigate'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
cop/team.rb:120:in `investigate'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
cop/team.rb:108:in `offenses'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
cop/team.rb:51:in `inspect_file'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
runner.rb:243:in `inspect_file'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
runner.rb:190:in `block in do_inspection_loop'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
runner.rb:222:in `block in iterate_until_no_changes'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
runner.rb:215:in `loop'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
runner.rb:215:in `iterate_until_no_changes'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
runner.rb:186:in `do_inspection_loop'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
runner.rb:101:in `block in file_offenses'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
runner.rb:111:in `file_offense_cache'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
runner.rb:99:in `file_offenses'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
runner.rb:90:in `process_file'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
runner.rb:68:in `block in each_inspected_file'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
runner.rb:65:in `each'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
runner.rb:65:in `reduce'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
runner.rb:65:in `each_inspected_file'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
runner.rb:57:in `inspect_files'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
runner.rb:36:in `run'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
cli.rb:72:in `execute_runner'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/lib/rubocop/
cli.rb:27:in `run'
/Users/andrew/workspace/standfast/.gems/gems/rubocop-0.46.0/bin/rubocop:
13:in `block in <top (required)>
```